{
 "title": "envoy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(envoy_cluster_name)"
    }
   },
   {
    "name": "http_conn_manager_prefix",
    "query": {
     "query": "label_values(envoy_http_conn_manager_prefix)"
    }
   },
   {
    "name": "listener_address",
    "query": {
     "query": "label_values(envoy_listener_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "envoy_server_total_connections", "legendFormat": "__auto" }
   ]
  },
  { "title": "upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Upstream cx active and buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_upstream_cx_rx_bytes_buffered{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_upstream_cx_tx_bytes_buffered{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream cx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_connect_fail{envoy_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_connect_timeout{envoy_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_destroy{envoy_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_destroy_local{envoy_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{envoy_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_destroy_with_active_rq{envoy_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_destroy_remote{envoy_cluster_name=~\"$cluster_name\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream rq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_upstream_rq_cancelled{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_upstream_rq_max_duration_reached{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_upstream_rq_timeout{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream rq total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_failure_eject[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_external_upstream_rq_xx[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_external_upstream_rq_completed[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_external_upstream_rq[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream overflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_overflow",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Downstream cx and buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_active{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_http_downstream_cx_rx_bytes_buffered{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_listener_downstream_cx_active{envoy_listener_address=~\"$envoy_listener_address\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_listener_worker_0_downstream_cx_active{envoy_listener_address=~\"$envoy_listener_address\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_listener_worker_1_downstream_cx_active{envoy_listener_address=~\"$envoy_listener_address\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream cx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_downstream_cx_connect_fail[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_cluster_downstream_cx_connect_timeout[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_destroy{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_destroy_local[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_destroy_local_with_active_rq[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_destroy_with_active_rq[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_destroy_remote{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_delayed_close_timeout{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream rq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_http1_active{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_http_downstream_rq_active{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream rq total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_completed{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_http1_total{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_response_before_rq_complete{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_rx_reset{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_listener_downstream_cx_destroy{envoy_listener_address=~\"$envoy_listener_address\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_listener_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "envoy_http_downstream_cx_ssl_active{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=~\"$http_conn_manager_prefix\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Circuit breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Circuit breakers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_cx{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_rq{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_cx{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_rq{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_pending{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_pending{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_cx_pools{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_cx_pools{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit breaker remaining retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_retries{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_retries{envoy_cluster_name=~\"$cluster_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "envoy_filesystem_write_total_buffered",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_filesystem_write_buffered[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    { "expr": "envoy_server_memory_allocated", "legendFormat": "__auto" },
    { "expr": "envoy_server_memory_heap_size", "legendFormat": "__auto" },
    {
     "expr": "envoy_server_memory_physical_size",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}