global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'envoy_downstream'
    static_configs:
      - targets: ['envoy_downstream:9901']
    metrics_path: /stats/prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: job
        replacement: envoy_downstream

  - job_name: 'envoy_upstream'
    static_configs:
      - targets: ['envoy_upstream:9901']
    metrics_path: /stats/prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: job
        replacement: envoy_upstream
